[package]
name = "reduce-runner"
version = "0.1.0"
authors = ["Mateusz Na≈õciszewski <matin1111@wp.pl>"]

[[bin]]
name = "reducewrap"
path = "src/main.rs"

[dependencies]
fs_extra = "1.0.0"
clap = "2.26.0"
tempdir = "0.3.0"
